name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '6,26,46 */6 * * *'


jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        curl 'https://data.calgary.ca/resource/gzkz-5k9a.json?$limit=5000' \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "X-App-Token: ${{secrets.CALGARY_SHORT_RENTALS_APP_TOKEN}}" \
          -X GET --data-raw 'showFeatured=False' | jq > calgary-short-rentals.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
